export type GameCategory = 'all' | 'brain' | 'classic' | 'action' | 'puzzle'

export interface GameDef {
  id: string
  name: string
  description: string
  category: Exclude<GameCategory, 'all'>
  difficulty: 'Easy' | 'Medium' | 'Hard'
  xpMultiplier: number
  available: boolean   // false = coming soon
}

export const GAMES: GameDef[] = [
  // ── BRAIN TRAINING ─────────────────────────────────────────────────────────
  {
    id: 'memory-matrix',
    name: 'Memory Matrix',
    description: 'Memorize a grid of lit cells, reproduce the pattern.',
    category: 'brain',
    difficulty: 'Medium',
    xpMultiplier: 1.1,
    available: true,
  },
  {
    id: 'lowdown',
    name: 'Lowdown',
    description: 'Higher or lower? Quick math under pressure.',
    category: 'brain',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'dual-n-back',
    name: 'Dual N-Back',
    description: 'Track two simultaneous sequences in working memory.',
    category: 'brain',
    difficulty: 'Hard',
    xpMultiplier: 1.8,
    available: true,
  },
  {
    id: 'color-stroop',
    name: 'Color Stroop',
    description: 'Name the ink color, not the word — fight your brain.',
    category: 'brain',
    difficulty: 'Medium',
    xpMultiplier: 1.0,
    available: true,
  },
  {
    id: 'number-flow',
    name: 'Number Flow',
    description: 'Mental arithmetic chains under time pressure.',
    category: 'brain',
    difficulty: 'Medium',
    xpMultiplier: 1.2,
    available: true,
  },
  {
    id: 'pattern-sync',
    name: 'Pattern Sync',
    description: 'Complete visual sequences before they vanish.',
    category: 'brain',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'focus-grid',
    name: 'Focus Grid',
    description: 'Spot the odd element in a shifting grid.',
    category: 'brain',
    difficulty: 'Easy',
    xpMultiplier: 0.8,
    available: true,
  },
  {
    id: 'speed-sort',
    name: 'Speed Sort',
    description: 'Classify shapes and colors with a single tap.',
    category: 'brain',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'word-fresh',
    name: 'Word Fresh',
    description: 'Catch falling letters and form words before they pile up.',
    category: 'brain',
    difficulty: 'Medium',
    xpMultiplier: 1.1,
    available: true,
  },
  {
    id: 'low-pop',
    name: 'Low Pop',
    description: 'Tap numbered hexagons in ascending order.',
    category: 'brain',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'word-flux',
    name: 'Word Flux',
    description: 'Build words from a shrinking pool of letters.',
    category: 'brain',
    difficulty: 'Medium',
    xpMultiplier: 1.0,
    available: false,
  },
  // ── CLASSIC ARCADE ─────────────────────────────────────────────────────────
  {
    id: 'nimtris',
    name: 'Nimtris',
    description: 'Classic falling-block puzzle. Clear lines, chain combos.',
    category: 'classic',
    difficulty: 'Medium',
    xpMultiplier: 1.2,
    available: true,
  },
  {
    id: 'hexfall',
    name: 'Hex Fall',
    description: 'Block-blast grid. Tap groups of 2+ to shatter them.',
    category: 'classic',
    difficulty: 'Easy',
    xpMultiplier: 1.0,
    available: true,
  },
  {
    id: 'snake-path',
    name: 'Snake Path',
    description: 'Grow without hitting walls or yourself.',
    category: 'classic',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'galaxy-defender',
    name: 'Galaxy Defender',
    description: 'Galaga-style shooter. Survive waves of alien ships.',
    category: 'classic',
    difficulty: 'Medium',
    xpMultiplier: 1.3,
    available: true,
  },
  {
    id: 'space-raid',
    name: 'Space Raid',
    description: 'Vertical shoot-em-up. Dodge and blast waves of enemies.',
    category: 'classic',
    difficulty: 'Medium',
    xpMultiplier: 1.1,
    available: true,
  },
  {
    id: 'breakwall',
    name: 'Breakwall',
    description: 'Smash all bricks with the ball. Don\'t let it drop.',
    category: 'classic',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'frog-cross',
    name: 'Frog Cross',
    description: 'Cross the road and river without getting hit.',
    category: 'classic',
    difficulty: 'Easy',
    xpMultiplier: 0.8,
    available: true,
  },
  {
    id: 'pong-duel',
    name: 'Pong Duel',
    description: 'Classic 1v1 paddle battle, now online.',
    category: 'classic',
    difficulty: 'Easy',
    xpMultiplier: 1.0,
    available: true,
  },
  // ── ACTION ─────────────────────────────────────────────────────────────────
  {
    id: 'runner',
    name: 'Hex Runner',
    description: 'Endless side-scroller. Jump obstacles, go further.',
    category: 'action',
    difficulty: 'Hard',
    xpMultiplier: 1.5,
    available: true,
  },
  {
    id: 'quicktap',
    name: 'Quick Tap',
    description: 'Tap targets before they vanish. Pure reflex test.',
    category: 'action',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'gravity-switch',
    name: 'Gravity Switch',
    description: 'Flip gravity to survive a corridor of spikes.',
    category: 'action',
    difficulty: 'Hard',
    xpMultiplier: 1.6,
    available: true,
  },
  {
    id: 'neon-blade',
    name: 'Neon Blade',
    description: 'Swipe to slice incoming objects, miss nothing.',
    category: 'action',
    difficulty: 'Medium',
    xpMultiplier: 1.2,
    available: true,
  },
  {
    id: 'dodge-storm',
    name: 'Dodge Storm',
    description: 'Survive waves of projectiles using only movement.',
    category: 'action',
    difficulty: 'Hard',
    xpMultiplier: 1.5,
    available: true,
  },
  {
    id: 'tower-stack',
    name: 'Tower Stack',
    description: 'Drop moving blocks to build the tallest tower.',
    category: 'action',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  // ── PUZZLE ─────────────────────────────────────────────────────────────────
  {
    id: 'memory',
    name: 'Memory Rush',
    description: 'Flip cards to match pairs before the clock hits zero.',
    category: 'puzzle',
    difficulty: 'Easy',
    xpMultiplier: 0.8,
    available: true,
  },
  {
    id: 'perilous-path',
    name: 'Perilous Path',
    description: 'Memorize mines, then navigate A to B from memory.',
    category: 'puzzle',
    difficulty: 'Medium',
    xpMultiplier: 1.2,
    available: true,
  },
  {
    id: 'mini-sudoku',
    name: 'Mini Sudoku',
    description: 'Quick 4×4 and 6×6 Sudoku puzzles against the clock.',
    category: 'puzzle',
    difficulty: 'Medium',
    xpMultiplier: 1.1,
    available: true,
  },
  {
    id: 'merge-hex',
    name: 'Merge Hex',
    description: '2048 on a hexagonal grid. Merge to reach 4096.',
    category: 'puzzle',
    difficulty: 'Medium',
    xpMultiplier: 1.2,
    available: true,
  },
  {
    id: 'color-path',
    name: 'Color Path',
    description: 'Draw lines to connect matching colors without crossing.',
    category: 'puzzle',
    difficulty: 'Easy',
    xpMultiplier: 0.9,
    available: true,
  },
  {
    id: 'shift-blocks',
    name: 'Shift Blocks',
    description: 'Slide pieces to clear the board in minimum moves.',
    category: 'puzzle',
    difficulty: 'Medium',
    xpMultiplier: 1.1,
    available: true,
  },
  {
    id: 'hex-flow',
    name: 'Hex Flow',
    description: 'Rotate pipes to guide liquid to every outlet.',
    category: 'puzzle',
    difficulty: 'Medium',
    xpMultiplier: 1.0,
    available: true,
  },
  {
    id: 'light-bounce',
    name: 'Light Bounce',
    description: 'Place mirrors so a beam hits every crystal.',
    category: 'puzzle',
    difficulty: 'Hard',
    xpMultiplier: 1.4,
    available: true,
  },
  {
    id: 'sum-path',
    name: 'Sum Path',
    description: 'Trace a path through the grid that hits the target sum.',
    category: 'puzzle',
    difficulty: 'Hard',
    xpMultiplier: 1.5,
    available: true,
  },
]

export const CATEGORIES: { id: GameCategory; label: string }[] = [
  { id: 'all',     label: 'All' },
  { id: 'brain',   label: 'Brain' },
  { id: 'classic', label: 'Classic' },
  { id: 'action',  label: 'Action' },
  { id: 'puzzle',  label: 'Puzzle' },
]

export const DIFFICULTY_COLOR: Record<string, string> = {
  Easy:   'var(--green)',
  Medium: 'var(--gold)',
  Hard:   'var(--red)',
}
